services:
  - type: web
    name: stock-tracker
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
